### ISSUE TITLE
Can't handle hyphens, underscore and emojis

### ISSUE THREAD

**Issue by tklae** [aus-der-Technik/EnvCraft#1]
If I create a sample file with the following content:
```
api-key=
USER_CREDENTIALS
😃=
```
The script fails with three different problems:
- For the hypen in `api-key` it throws an error: `/opt/homebrew/bin/envcraft: line 114: api-key: invalid variable name`
- The underscore in `USER_CREDENTIALS` is stripped away and becomes `USERCREDENTIALS` in the target file
- The emoji is just skipped (if I move it to the middle of the variables the remaining ones are still executed so it doesn't crash the entire script)

**Comment by KrisSimon** [comment]
Thank you for report the three issues. 
I will take a look into it.

**Comment by KrisSimon** [comment]
@tklae I added three new tests for all of your reported issues. All tests pass. Please take a look into it and see if it runs on your machine, too. 
Let's find the differences together. Can you prepare a pull request with tests that do not pass based on the branch: [1-cant-handle-hyphens-underscore-and-emojis](https://github.com/aus-der-Technik/EnvCraft/tree/1-cant-handle-hyphens-underscore-and-emojis)?

**Comment by tklae** [comment]
The tests don't pass on my machine unfortunately (M1 Macbook):
```
spawn ./envcraft.sh /Users/tklae/projects/adt/git/envcraft-github/tests/samples/.env.with-hyphens.sample.expected /Users/tklae/projects/adt/git/envcraft-github/results/.env.with-hyphens.result
./envcraft.sh: line 114: api-key: invalid variable name
send: spawn id exp6 not open
    while executing
"send -- "my-shiny-new-api-key\n"
```
and 
```
spawn ./envcraft.sh /Users/tklae/projects/adt/git/envcraft-github/tests/samples/.env.with-emojis.sample.expected /Users/tklae/projects/adt/git/envcraft-github/results/.env.with-emojis.result
./envcraft.sh: line 114: 😃: invalid variable name
send: spawn id exp6 not open
    while executing
```

**Comment by tklae** [comment]
If I run it with the system version of bash instead of a newer homebrew version it works.

System version:
```
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Homebrew version:
```
GNU bash, version 5.2.26(1)-release (aarch64-apple-darwin23.2.0)
```
